rules:
  description-empty: 
    level: error
  subject-empty: 
    level: error
  body-empty:
    level: error
  scope:
    level: error
    optional: false
    options:
      - docs
      - ci
      - misc
      - code
      - test
      {% if include_bin %}
      - cli
      {% endif %}
  type:
    level: error
    optional: false
    options:
      - feat
      - fix
      - chore
