[template]
cargo_generate_version = ">=0.9.0"
exclude                = [".github/workflows/test.yml", ".github/workflows/check.yml"]

[placeholders]
include_async = { type = "bool", prompt = "Do you want it to be async?", default = false }
include_bin = { type = "bool", prompt = "Include a binary?", default = true }
serde_format = { type = "array", prompt = "Which serde format would you like?", choices = [
  "TOML",
  "JSON",
  "YAML",
  "CBOR",
], default = [
  "TOML",
] }

repo_url    = { type = "string", prompt = "Where will the repo be hosted?", default = "https://github.com/{{username}}/{{project-name}}" }
docs_url    = { type = "string", prompt = "Where will the docs be hosted?", default = "https://docs.rs/{{crate_name}}" }
description = { type = "string", prompt = "Project description:", defaults = "" }


[conditional.'include_bin'.placeholders.bin_name]
type    = "string"
prompt  = "What should the binary be called?"
default = "{{crate_name}}"


[hooks]
