[template]
cargo_generate_version = ">=0.9.0"

[placeholders]
include_logging = { type = "bool", prompt = "Do you want logging?", default = true }
include_cli = { type = "bool", prompt = "Do you want a cli?", default = true }
include_serde = { type = "bool", prompt = "Do you want serde?", default = true }

[conditional.'include_logging'.placeholders.logger_kind]
type = "string"
prompt = "Simple or tracing logger?"
choices = ["simple", "tracing"]

[conditional.'include_serde'.placeholders.serde_format]
type = "string"
prompt = "Which serde format would you like?"
choices = ["JSON", "YAML", "TOML", "CBOR"]


[hooks]
# pre = ["ask-license.rhai"]
