[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2024"
rust-version = "1.76"
description = ""
readme = "README.md"
repository = "https://github.com/9999years/rust-cli-template"
license = "MIT"                                               # https://spdx.org/licenses/

[[bench]]
name = "main"
harness = false

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "{{project-name}}"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4", features = ["derive", "unicode", "cargo"] }
tracing = { version = "0", features = ["attributes"] }
tracing-subscriber = "0"
tracing-error = "0"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
criterion = "0"
